-- AlterTable
ALTER TABLE "caravans" ADD COLUMN "totalCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "caravans" ADD COLUMN "maleCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "caravans" ADD COLUMN "femaleCount" INTEGER NOT NULL DEFAULT 0;
